# Copyright (c) 2024 Typox Project Contributors
# Licensed under the MIT License - see LICENSE file for details

[package]
name = "oxload"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Typox Project Contributors"]
license = "MIT"
description = "Load RDF data from Oxigraph stores into Typst documents"
repository = "https://github.com/deepthought-solutions/typox"
keywords = ["rdf", "sparql", "oxigraph", "data"]

[tool.typst-ts]
exclude = ["target/"]