# Copyright (c) 2024 Typox Project Contributors
# Licensed under the MIT License - see LICENSE file for details

[package]
name = "typox-rdf"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Typox Project Contributors"]
license = "MIT"
description = "Query RDF data with SPARQL and load results."
repository = "https://github.com/deepthought-solutions/typox"
keywords = ["rdf", "sparql", "oxigraph", "data"]
categories = ["integration", "model"]